### ISSUE TITLE
_Static_assert failure displays incorrect message

### ISSUE THREAD

**Issue by ehaas** [Vexu/arocc#22]
```C
_Static_assert(1 == 0, "They are not equal!");
```

Output:
```
/Users/ehaas/source/c/test.c:1:1: error: static assertion failed "\xaa\xaa\xaa\xaa\xaa\x00\x00 \x00\x00\x00\x00\x00\x00\x00 \x05\x00\xaa"
_Static_assert(1 == 0, "They are not equal!");
^
1 error generated.
static_assert: 'void'
 condition:
  equal_expr: 'int' (value: 0)
   lhs:
    int_literal: 'int'
     value: 1
   rhs:
    int_literal: 'int'
     value: 0
 diagnostic:
  string_literal_expr: '[20]char' lvalue
   data: "They are not equal!"
```
