### ISSUE TITLE
Crash: invalid type specifier combination in function definition 

### ISSUE THREAD

**Issue by ehaas** [Vexu/arocc#272]
The following crashes when using `--verbose-ast`:

```c
char int foo(void) {
    return 0;
}
```

```
thread 41735095 panic: reached unreachable code
/Users/ehaas/source/arocc/src/Value.zig:62:17: 0x100de85b2 in Value.signExtend (arocc)
        else => unreachable,
                ^
/Users/ehaas/source/arocc/src/Value.zig:489:46: 0x100d8685b in Value.dump (arocc)
            try w.print("{d}", .{v.signExtend(ty, comp)});
                                             ^
/Users/ehaas/source/arocc/src/Tree.zig:657:21: 0x100d37d81 in Tree.dumpNode (arocc)
        try val.dump(ty, tree.comp, w);
                    ^
/Users/ehaas/source/arocc/src/Tree.zig:950:34: 0x100d401e0 in Tree.dumpNode (arocc)
                try tree.dumpNode(data.un, level + delta, w);
                                 ^
```

**Comment by ehaas** [comment]
`char int` was a red herring; the actual issue was with returning an int literal from a function with `char` return value, e.g. the following would also cause the crash:
```c
char foo(void) {
    return 0;
}
```
The problem can be seen with `--verbose-ast` for any function that intCast's a literal as part of the return statement (`1` is saved twice):
```c
long foo(void) {
    return 1;
}
```

```
fn_def: 'fn () long'
 name: foo
 body:
  compound_stmt_two: 'void'
    return_stmt: 'void'
     expr:
      int_cast: 'long' (value: 1)
        int_literal: 'int' (value: 1)
```
