### ISSUE TITLE
Spurious warning when assignment increases qualifiers

### ISSUE THREAD

**Issue by ehaas** [Vexu/arocc#28]
I believe this is the opposite of #25

```C
void foo(void) {
   char *bar = 0;
   const char *baz = bar;
}
```

```
/Users/ehaas/source/c/test.c:3:22: warning: initializing 'const char *' from incompatible type 'char *' discards qualifiers
   const char *baz = bar;
                     ^
1 warning generated.
fn_def: 'fn () void'
 name: foo
 body:
  compound_stmt: 'void'
    var: '*char'
     name: bar
     init:
      null_to_pointer: '*char'
        int_literal: 'int'
         value: 0

    var: '*const char'
     name: baz
     init:
      lval_to_rval: '*char'
        decl_ref_expr: '*char' lvalue
         name: bar

    implicit_return: 'void'
```
