### ISSUE TITLE
Enum & Struct Declarations don't seem to be parsed correctly

### ISSUE THREAD

**Issue by moosichu** [Vexu/arocc#3]
When feeding in a source file containing an enum, it seems to be treated as an int var?

With the following input:

```
int IntTest;

enum EnumTest
{
    Begin,
    End,
};

struct StructTest{
    int MemberTest;
};
```

You get the following output:

```
var: 'int'
 name: IntTest

var: 'int'
 name: EnumTest

var: 'int'
 name: StructTest
```

**Comment by Vexu** [comment]
`int` is the default type of all variables in C. The reason enums and structs aren't parsed correctly is because they aren't being parsed at all.

**Comment by Vexu** [comment]
I implemented parsing records and enums and your example now looks like this:
```c
int IntTest;

enum EnumTest
{
    Begin,
    End = 2,
};

struct StructTest{
    int MemberTest;
    _Static_assert(1, "foo");
};
```
```
var: 'int'
 name: IntTest

enum_decl_two: 'enum EnumTest'
  enum_field_decl: 'int'
   name: Begin
  enum_field_decl: 'int'
   name: End
   value:
    int_literal: 'int'
     value: 2

struct_decl_two: 'struct StructTest'
  record_field_decl: 'int'
   name: MemberTest
  static_assert: 'void'
   condition:
    int_literal: 'int'
     value: 1
   diagnostic:
    string_literal_expr: '[4]char' lvalue
     data: "foo"

```

I've also improved the test harness and added github actions, so contributing should be easier if you are interested (though plenty of cleanup is still required in `Parser`).
