### ISSUE TITLE
Parser.EatToken() can end-up out of bounds - not sure why

### ISSUE THREAD

**Issue by moosichu** [Vexu/arocc#32]
Specifically `p.tok_i` can end-up out of bounds in this conditional
```
if (p.tok_ids[p.tok_i] == id)
```
I've been able to workaround this issue locally by changing the condition of the while loop in Parser.zig to:
```zig
 while ((p.tok_i < p.tok_ids.len) and (p.eatToken(.eof) == null))
 ```
 I've been using a small amount of macro-trickery (in an attempt) to use arocc for build-time reflection on C-style enums, whilst still supporting C++ style enums for the actual C++ side of things. So the code that is being parsed is a little idiosyncratic:
 
```C
#pragma once

#include "Reflection/Enum.meta.h"

DECLARE_ENUM(LogChannel, uint16_t)
{
    Default = 0,
    Rendering = 1,
    Vulkan = 2,
    VulkanInternal = 3,
    Import = 4,
    JobSystem = 5,
    Containers = 6,
    Engine = 7,
};
```

Where `Enum.meta.h` is defined as:
```C
#pragma once

#ifdef __cplusplus
#include "cstdint_wrapper.hpp"
#define DECLARE_ENUM(EnumName, EnumType) \
    enum class EnumName : EnumType
#else
#define DECLARE_ENUM(EnumName, EnumType) \
    enum EnumName
#endif
```

I've done a little bit of debugging to try and track down the cause - but I don't want to spend too much time being side-tracked by this problem. So I will leave it for now - so thought I would at least make the issue. I might come back to it later but I need to dedicate some time to properly understanding how arocc is structured in order to debug this issue.

**Comment by doppioandante** [comment]
Does the snippet of code here reproduce the issue? I'll take a look at it while I mess with the rest of the macro expansion stuff.

**Comment by Vexu** [comment]
Can't reproduce with latest master:
```
zig build run -- a.c --verbose-ast
enum_decl: 'enum LogChannel'
  enum_field_decl: 'int'
   name: Default
   value:
    int_literal: 'int' (value: 0)
     value: 0

  enum_field_decl: 'int'
   name: Rendering
   value:
    int_literal: 'int' (value: 1)
     value: 1

  enum_field_decl: 'int'
   name: Vulkan
   value:
    int_literal: 'int' (value: 2)
     value: 2

  enum_field_decl: 'int'
   name: VulkanInternal
   value:
    int_literal: 'int' (value: 3)
     value: 3

  enum_field_decl: 'int'
   name: Import
   value:
    int_literal: 'int' (value: 4)
     value: 4

  enum_field_decl: 'int'
   name: JobSystem
   value:
    int_literal: 'int' (value: 5)
     value: 5

  enum_field_decl: 'int'
   name: Containers
   value:
    int_literal: 'int' (value: 6)
     value: 6

  enum_field_decl: 'int'
   name: Engine
   value:
    int_literal: 'int' (value: 7)
     value: 7

```
