### ISSUE TITLE
Compound literals do not initialize array members properly from strings

### ISSUE THREAD

**Issue by ehaas** [Vexu/arocc#537]
Looks like it tries to initialize the first member with a pointer and uses a filler for the rest.

```c
struct S {
    char bytes[32];
};

void foo(void) {
    struct S s = (struct S){"ABC"};
}
```

```
fn_def: 'fn () void'
 name: foo
 body:
  compound_stmt_two: 'void'
    var: 'struct S'
     name: s
     init:
      implicit_cast: (lval_to_rval) 'struct S'
        compound_literal_expr: 'struct S' lvalue
         struct_init_expr_two: 'struct S'
           array_init_expr_two: '[32]char'
             implicit_cast: (pointer_to_int) 'char'
               implicit_cast: (array_to_pointer) 'd[4]char'
                 string_literal_expr: '[4]char' lvalue (value: "ABC")
             array_filler_expr: 'char'
              count: 31
    implicit_return: 'void'

./test.c:7:29: warning: implicit pointer to integer conversion from 'char *' to 'char' [-Wint-conversion]
    struct S s = (struct S){"ABC"};
```
