### ISSUE TITLE
Crash: assign boolean or result to float

### ISSUE THREAD

**Issue by ehaas** [Vexu/arocc#668]
```c
void foo(void) {
    float f = 2.0 || 0;
}
```

```
panic: access of union field 'int' while field 'float' is active
/Users/ehaas/source/arocc/src/aro/Value.zig:205:46: 0x103d44402 in intToFloat (arocc)
    return switch (comp.interner.get(v.ref()).int) {
                                             ^
/Users/ehaas/source/arocc/src/aro/Parser.zig:5589:35: 0x103d15b0f in floatCast (arocc)
            try res.val.intToFloat(float_ty, p.comp);
                                  ^
/Users/ehaas/source/arocc/src/aro/Parser.zig:6086:34: 0x103ca033c in coerceExtra (arocc)
                try res.floatCast(p, unqual_ty);
                                 ^
```

**Comment by ehaas** [comment]
Seems like value is not getting truncated to int after logical or:

```c
_Static_assert(2.5 || 0, "");
```
```
static_assert: 'void'
 condition:
  implicit_cast: (int_to_bool) '_Bool'
    bool_or_expr: 'int' (value: 2.5)
     lhs:
      float_literal: 'double' (value: 2.5)
     rhs:
      implicit_cast: (int_to_float) 'double'
        int_literal: 'int' (value: 0)
 diagnostic:
  string_literal_expr: '[1]char' lvalue (value: "")
```
(note value of `bool_or_expr`)
