### ISSUE TITLE
Anonymous record in compound literal is added to the AST twice

### ISSUE THREAD

**Issue by Vexu** [Vexu/arocc#847]
```c
unsigned long foo(unsigned long x) {
    return ((union{unsigned long _x;}){x})._x;
}
```
```
fn_def: 'fn (x: unsigned long) unsigned long'
 name: foo
 body:
  compound_stmt
    union_decl: 'union (anonymous union at a.c:30:14)'
      record_field: 'unsigned long'
       name: _x

    union_decl: 'union (anonymous union at a.c:30:14)'
      record_field: 'unsigned long'
       name: _x

    return_stmt: 'unsigned long'
     expr:
      cast: (lval_to_rval) 'unsigned long'
        member_access_expr: 'unsigned long' lvalue
         lhs:
          paren_expr: 'union (anonymous union at a.c:30:14)' lvalue
           operand:
            compound_literal_expr: 'union (anonymous union at a.c:30:14)' lvalue
             union_init_expr: 'union (anonymous union at a.c:30:14)'
              field index: 0
               cast: (lval_to_rval) 'unsigned long'
                 decl_ref_expr: 'unsigned long' lvalue
                  name: x
         name: _x
```
